function pToFttettc(varargin);
% pToFttettc( [...] );
% TT Errors TTC
h = ne_dstat({
  'TTC_NoConn', 'TTC_ErrStat', 0; ...
	'TTC_PumpOT', 'TTC_ErrStat', 1; ...
	'TTC_CtrlOT', 'TTC_ErrStat', 2; ...
	'TTC_PwrFail', 'TTC_ErrStat', 3; ...
	'TTC_AuxFail', 'TTC_ErrStat', 4; ...
	'TTC_OverV', 'TTC_ErrStat', 5; ...
	'TTC_Short', 'TTC_ErrStat', 6; ...
	'TTC_OverLoad', 'TTC_ErrStat', 7; ...
	'TTC_LowBatt', 'TTC_ErrStat', 9; ...
	'TTC_BadTime', 'TTC_ErrStat', 10 }, 'TTC', varargin{:} );
