function pToFttw(varargin);
% pToFttw( [...] );
% Twis Torr W
h = timeplot({'TTA_W','TTB_W','TTC_W'}, ...
      'Twis Torr W', ...
      'W', ...
      {'TTA\_W','TTB\_W','TTC\_W'}, ...
      varargin{:} );
