function pToFtts(varargin);
% pToFtts( [...] );
% Twis Torr Speed
h = timeplot({'TTA_drvf','TTA_spd','TTB_drvf','TTB_spd','TTC_drvf','TTC_spd'}, ...
      'Twis Torr Speed', ...
      'Speed', ...
      {'TTA\_drvf','TTA\_spd','TTB\_drvf','TTB\_spd','TTC\_drvf','TTC\_spd'}, ...
      varargin{:} );
