function pToFtti(varargin);
% pToFtti( [...] );
% Twis Torr I
h = timeplot({'TTA_I','TTB_I','TTC_I'}, ...
      'Twis Torr I', ...
      'I', ...
      {'TTA\_I','TTB\_I','TTC\_I'}, ...
      varargin{:} );
