function pToFhzf(varargin);
% pToFhzf( [...] );
% Horiba Zero Flow 2
h = timeplot({'ZeroFlow2_SP','ZeroFlow2'}, ...
      'Horiba Zero Flow 2', ...
      'Zero Flow 2', ...
      {'ZeroFlow2\_SP','ZeroFlow2'}, ...
      varargin{:} );
