function pToFttt(varargin);
% pToFttt( [...] );
% Twis Torr T
h = timeplot({'TTA_T','TTB_T','TTC_T'}, ...
      'Twis Torr T', ...
      'T', ...
      {'TTA\_T','TTB\_T','TTC\_T'}, ...
      varargin{:} );
