function pToFhcd(varargin);
% pToFhcd( [...] );
% Horiba Cal Dil
h = timeplot({'CalDil_SP','CalDil'}, ...
      'Horiba Cal Dil', ...
      'Cal Dil', ...
      {'CalDil\_SP','CalDil'}, ...
      varargin{:} );
