function pToFtt_v(varargin);
% pToFtt_v( [...] );
% Twis Torr V
h = timeplot({'TTA_V','TTB_V','TTC_V'}, ...
      'Twis Torr V', ...
      'V', ...
      {'TTA\_V','TTB\_V','TTC\_V'}, ...
      varargin{:} );
