function pToFttc(varargin);
% pToFttc( [...] );
% Twis Torr Cflags
h = ne_dstat({
  'TTC_Start', 'TTC_flags', 0; ...
	'TTC_Speed', 'TTC_flags', 1; ...
	'TTC_WtrCl', 'TTC_flags', 2; ...
	'TTC_ActStp', 'TTC_flags', 3; ...
	'TTC_VentVlv', 'TTC_flags', 4; ...
	'TTC_VentOp', 'TTC_flags', 5; ...
	'TTC_Resp', 'TTC_flags', 7 }, 'Cflags', varargin{:} );
